FROM golang:1.15-alpine3.12

RUN apk update upgrade
RUN apk add git

RUN go get -u github.com/go-delve/delve/cmd/dlv
RUN go get github.com/BurntSushi/toml
RUN go get github.com/howeyc/fsnotify
RUN go get github.com/mattn/go-colorable

WORKDIR /go/src/github.com/CMSgov/bcda-app
COPY . .

WORKDIR /go/src/github.com/CMSgov/bcda-app/bcdaworker
RUN go install
CMD ["dlv", "--listen=:2345",  "--headless=true",  "--accept-multiclient", "--api-version=2", "exec", "--continue", "/go/bin/bcdaworker"]